name: "Publish Maven Artifacts"
description: "Publish maven artifacts to central repository"

inputs:
  gpg-private-key:
    description: the gpg private key used to publish
    required: true
  gpg-passphrase:
    description: the gpg passphrase used to publish
    required: true
  username:
    description: the username
    required: true
  password:
    description: the password
    required: true

runs:
  using: "composite"
  steps:

  - uses: eclipse-edc/.github/.github/actions/import-gpg-key@main
    with:
      gpg-private-key: ${{ inputs.gpg-private-key }}

  - name: Publish to maven central
    shell: bash
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ inputs.username }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ inputs.password }}

      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ inputs.gpg-private-key }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ inputs.gpg-passphrase }}
    run: ./gradlew publishToMavenCentral -Psigning.gnupg.executable=gpg -Psigning.gnupg.passphrase="${{ inputs.gpg-passphrase }}"
 
