name: "Set project version"
description: "Sets the project version"

inputs:
  version:
    description: The version to be set in the project.
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: read version from gradle.properties
      shell: bash
      run: |
        # updates the project version
        sed -i 's#^version=.*#version='"${{ inputs.version }}"'#g' $(find . -name "gradle.properties")
        
        # updates the eventual core library version in the version catalog
        sed -i 's#^edc\s*=\s*.*#edc = "'"${{ inputs.version }}"'"#g' gradle/libs.versions.toml
        
        # updates the versions in the DEPENDENCIES file, if it exists
        sed -i "s#maven/mavencentral/org.eclipse.edc/\(.*\)/\([^,]*\),\(.*\)#maven/mavencentral/org.eclipse.edc/\1/${{ inputs.version }},\3#g" DEPENDENCIES || true
