name: 'Dependency Review'
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  trigger-workflow:
    uses: eclipse-edc/.github/.github/workflows/dependency-check.yml@main