name: Create EDC Component Release

on:
  workflow_dispatch:
    inputs:
      component_version:
        description: 'Version string that is used for publishing (e.g. "1.0.0", NOT "v1.0.0"). Appending -SNAPSHOT will create a snapshot release.'
        required: true
        type: string


env:
  COMPONENT_VERSION: ${{ github.event.inputs.component_version || inputs.component_version }}

jobs:
  trigger-workflow:
    uses: eclipse-edc/.github/.github/workflows/release-component.yml@main
    with:
      component_version: ${{ env.COMPONENT_VERSION }}
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}