name: Scan Pull Request

on:
  pull_request:
    branches: [ main ]
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger-workflow:
    uses: ./.github/workflows/scan-pull-request.yml@main
    secrets:
      envGH: ${{ secrets.GITHUB_TOKEN }}