name: "Create Snapshot Build"

on:
  push:
    branches:
      - main

jobs:
  trigger-workflow:
    uses: ./.github/workflows/trigger-snapshot.yml@main
    with:
      github_repository: ${{ github.repository }}
    secrets:
      jenkins_user: ${{ secrets.EF_JENKINS_USER }}
      jenkins_token: ${{ secrets.EF_JENKINS_TOKEN }}