name: Verify and Publish OpenAPI Specs

on:
  workflow_call:
    inputs:
      version:
        required: true
        description: "The version under which the API should be published"
        type: string
      apiGroup:
        required: true
        description: "The api group to be published"
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Publish-To-SwaggerHub:
    runs-on: ubuntu-latest
    env:
      rootDir: resources/openapi/yaml/${{ matrix.apiGroup }}
      SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_TOKEN }}
      SWAGGERHUB_USER: ${{ secrets.SWAGGERHUB_USER }}
      VERSION: ${{ github.event.inputs.version || inputs.version }}
      API_GROUP: ${{ github.event.inputs.apiGroup || inputs.apiGroup }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-build
      - uses: actions/setup-node@v4

      # merge together all api groups
      - name: Generate API Specs
        run: |
          # give option to override
          cmd=""
          if [ ! -z $VERSION ]; then
            cmd="-Pversion=$VERSION"
          fi
          ./gradlew resolve
          ./gradlew ${cmd} -PapiTitle="${{ env.API_GROUP }}" -PapiDescription="REST API documentation for the ${{ env.API_GROUP }}" :mergeApiSpec --input=resources/openapi/yaml/${{ env.API_GROUP }} --output=${{ env.API_GROUP }}.yaml

      # install swaggerhub CLI
      - name: Install SwaggerHub CLI
        run: npm i -g swaggerhub-cli

      # create API, will fail if exists
      - name: Create API
        continue-on-error: true
        run: |
          swaggerhub api:create ${{ env.SWAGGERHUB_USER }}/${{ env.API_GROUP }} -f ${{ env.API_GROUP }}.yaml --visibility=public --published=unpublish

      # Post snapshots of the API to SwaggerHub as "unpublished", because published APIs cannot be overwritten
      - name: Publish API Specs to SwaggerHub
        run: |
          # coalesce $VERSION, or whatever's stored in gradle.properties
          vers=${VERSION:-$(grep "version" gradle.properties  | awk -F= '{print $2}')}

          if [[ $vers != *-SNAPSHOT ]]; then
            echo "no snapshot, will set the API to 'published'";
            swaggerhub api:update ${{ env.SWAGGERHUB_USER }}/${{ env.API_GROUP }} -f ${{ env.API_GROUP }}.yaml --visibility=public --published=publish
            swaggerhub api:setdefault ${{ env.SWAGGERHUB_USER }}/${{ env.API_GROUP }}/$vers
          else
            echo "snapshot, will set the API to 'unpublished'";
            swaggerhub api:update ${{ env.SWAGGERHUB_USER }}/${{ env.API_GROUP }} -f ${{ env.API_GROUP }}.yaml --visibility=public --published=unpublish
          fi
