---
name: "Bump version (manually)"

on:
  workflow_call:
    inputs:
      target_branch:
        required: false
        type: string

jobs:
  Bump-Version:
    name: 'Update snapshot version'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bump-version
        name: Bump version
        with:
          target_branch: ${{ inputs.target_branch }}