---
name: "Bump version (manually)"

on:
  workflow_call:
    inputs:
      target_branch:
        required: false
        type: string

jobs:
  Bump-Version:
    name: 'Update snapshot version'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-edc/.github/.github/actions/bump-version@main
        name: Bump version
        with:
          target_branch: ${{ inputs.target_branch }}