name: Release

on:
  workflow_call:
    inputs:
      publish-autodoc:
        type: boolean
        description: whether publish autodoc or not
        default: false

jobs:

  create-tag:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.set-version.outputs.VERSION }}
      TAG: ${{ steps.set-tag.outputs.TAG }}
    steps:
      - uses: actions/checkout@v4
      - id: set-version
        run: |
          VERSION=$(echo ${{ github.ref }} | cut -d '/' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - uses: eclipse-edc/.github/.github/actions/set-project-version@main
        with:
          version: ${{ steps.set-version.outputs.VERSION }}
      - shell: bash
        id: set-tag
        run: |
          git config user.name "eclipse-edc-bot"
          git config user.email "edc-bot@eclipse.org"
          
          TAG=v${{ steps.set-version.outputs.VERSION }}

          git add .
          git commit -m "Release Version $TAG" 

          git tag $TAG
          git push --atomic origin ${{ github.ref }} $TAG
          
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

  create-github-release:
    needs: [ Create-Tag ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ needs.Create-Tag.outputs.TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          removeArtifacts: true

  publish-autodoc:
    if: inputs.publish-autodoc == true
    uses: eclipse-edc/.github/.github/workflows/publish-autodoc.yml@main
    secrets: inherit
