name: 'Discord Webhook'

on:
  workflow_call:
    inputs:
      event-name:
        required: true
      event:
        required: true
    secrets:
      envDiscord:
        required: true

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: New Discussion
        uses: tsickert/discord-webhook@v5.3.0
        if: ${{ (input.event-name == 'discussion') }}
        with:
          webhook-url: ${{ secrets.envDiscord }}
          avatar-url: https://avatars.githubusercontent.com/u/9919?s=200&v=4
          embed-author-name: ${{ input.event.sender.login }}
          embed-author-url: ${{ input.event.sender.html_url }}
          embed-author-icon-url: ${{ input.event.sender.avatar_url }}
          embed-title: ${{ input.event.discussion.title }}
          embed-url: ${{ input.event.discussion.html_url }}
          embed-description: A **discussion** has been created in ${{ input.repository }}.

      - name: New Issue
        uses: tsickert/discord-webhook@v5.3.0
        if: ${{ (input.event-name == 'issues') }}
        with:
          webhook-url: ${{ secrets.envDiscord }}
          avatar-url: https://avatars.githubusercontent.com/u/9919?s=200&v=4
          embed-author-name: ${{ input.event.sender.login }}
          embed-author-url: ${{ input.event.sender.html_url }}
          embed-author-icon-url: ${{ input.event.sender.avatar_url }}
          embed-title: ${{ input.event.issue.title }}
          embed-url: ${{ input.event.issue.html_url }}
          embed-description: An **issue** has been opened in ${{ input.repository }}.

      - name: New Pull Request
        uses: tsickert/discord-webhook@v5.3.0
        if: ${{ (input.event-name == 'pull_request_target') }}
        with:
          webhook-url: ${{ secrets.envDiscord }}
          avatar-url: https://avatars.githubusercontent.com/u/9919?s=200&v=4
          embed-author-name: ${{ input.event.sender.login }}
          embed-author-url: ${{ input.event.sender.html_url }}
          embed-author-icon-url: ${{ input.event.sender.avatar_url }}
          embed-title: ${{ input.event.pull_request.title }}
          embed-url: ${{ input.event.pull_request.html_url }}
          embed-description: A **pull request** has been opened in ${{ input.repository }}.
