name: 'Discord Webhook'

on:
  workflow_call:
    inputs:
      event_discussion_html_url:
        required: true
        type: string
      event_discussion_title:
        required: true
        type: string
      event_issue_html_url:
        required: true
        type: string
      event_issue_title:
        required: true
        type: string
      event_name:
        required: true
        type: string
      event_pull_request_html_url:
        required: true
        type: string
      event_pull_request_title:
        required: true
        type: string
      event_sender_avatar_url:
        required: true
        type: string
      event_sender_html_url:
        required: true
        type: string
      event_sender_login:
        required: true
        type: string
      repository_name:
        required: true
        type: string
    secrets:
      env_discord:
        required: true

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: New Discussion
        uses: tsickert/discord-webhook@v5.3.0
        if: ${{ (inputs.event_name == 'discussion') }}
        with:
          webhook-url: ${{ secrets.env_discord }}
          avatar-url: https://avatars.githubusercontent.com/u/9919?s=200&v=4
          embed-author-name: ${{ inputs.event_sender_login }}
          embed-author-url: ${{ inputs.event_sender_html_url }}
          embed-author-icon-url: ${{ inputs.event_sender_avatar_url }}
          embed-title: ${{ inputs.event_discussion_title }}
          embed-url: ${{ inputs.event_discussion_html_url }}
          embed-description: A **discussion** has been created in ${{ inputs.repository_name }}.
          embed-color: 16305330

      - name: New Issue
        uses: tsickert/discord-webhook@v5.3.0
        if: ${{ (inputs.event_name == 'issues') }}
        with:
          webhook-url: ${{ secrets.env_discord }}
          avatar-url: https://avatars.githubusercontent.com/u/9919?s=200&v=4
          embed-author-name: ${{ inputs.event_sender_login }}
          embed-author-url: ${{ inputs.event_sender_html_url }}
          embed-author-icon-url: ${{ inputs.event_sender_avatar_url }}
          embed-title: ${{ inputs.event_issue_title }}
          embed-url: ${{ inputs.event_issue_html_url }}
          embed-description: An **issue** has been opened in ${{ inputs.repository_name }}.
          embed-color: 14023876

      - name: New Pull Request
        uses: tsickert/discord-webhook@v5.3.0
        if: ${{ (inputs.event_name == 'pull_request_target') }}
        with:
          webhook-url: ${{ secrets.env_discord }}
          avatar-url: https://avatars.githubusercontent.com/u/9919?s=200&v=4
          embed-author-name: ${{ inputs.event_sender_login }}
          embed-author-url: ${{ inputs.event_sender_html_url }}
          embed-author-icon-url: ${{ inputs.event_sender_avatar_url }}
          embed-title: ${{ inputs.event_pull_request_title }}
          embed-url: ${{ inputs.event_pull_request_html_url }}
          embed-description: A **pull request** has been opened in ${{ inputs.repository_name }}.
          embed-color: 7317724
