name: publish dependencies

on:
  workflow_call:

jobs:
  publish-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: eclipse-edc/.github/.github/actions/generate-dependencies-file@main

      - name: prepare deploy
        run: |
          mkdir public
          mv DEPENDENCIES public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          keep_files: true

  Post-To-Discord:
    needs: [ publish-dependencies ]
    if: "failure()"
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_GITHUB_CI_WEBHOOK }}
          status: ${{ needs.publish-dependencies.result }}
          title: "Generate ${{ github.repository }} dependencies"
          username: GitHub Actions
