name: "Publish Snapshot Build"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  Publish-Snapshot:
    name: "Publish artefacts to Snapshots repository"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - uses: eclipse-edc/.github/.github/actions/publish-maven-artifacts@main
        with:
          gpg-private-key: ${{ secrets.ORG_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.ORG_GPG_PASSPHRASE }}
          username: ${{ secrets.CENTRAL_SONATYPE_TOKEN_USERNAME }}
          password: ${{ secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD }}

