name: publish dependencies

on:
  workflow_call:

jobs:
  publish-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: Download latest Eclipse Dash
        run: |
          curl -L https://repo.eclipse.org/service/local/artifact/maven/redirect\?r\=dash-licenses\&g\=org.eclipse.dash\&a\=org.eclipse.dash.licenses\&v\=LATEST --output dash.jar
      - name: Generate DEPENDENCIES
        run: |
          ./gradlew allDependencies | grep -Poh "(?<=\s)[\w.-]+:[\w.-]+:[^:\s\[\]]+" | sort | uniq | java -jar dash.jar - -summary DEPENDENCIES || true

      - name: evaluate DEPENDENCIES
        run: |
          if ! [ -s DEPENDENCIES ];
          then
            echo "error: DEPENDENCIES file was not created correctly, please trigger the workflow again";
            exit 1;
          fi

          grep "restricted" DEPENDENCIES || true > RESTRICTED;
          if [ -s RESTRICTED ];
          then
            echo "warning: restricted dependencies found:";
            cat RESTRICTED;
          fi

          grep "rejected" DEPENDENCIES || true > REJECTED;
          if [ -s REJECTED ];
          then
            echo "error: rejected dependencies found:";
            cat REJECTED;
            exit 1;
          fi

      - name: prepare deploy
        run: |
          mkdir public
          mv DEPENDENCIES public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          keep_files: true

  Post-To-Discord:
    needs: [ publish-dependencies ]
    if: "failure()"
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_GITHUB_CI_WEBHOOK }}
          status: ${{ needs.publish-dependencies.result }}
          title: "Generate ${{ github.repository }} dependencies"
          username: GitHub Actions
