name: publish dependencies

on:
  workflow_call:

jobs:
  publish-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: eclipse-edc/.github/.github/actions/generate-dependencies-file@main

      - name: prepare deploy
        run: |
          mkdir public
          mv DEPENDENCIES public/

      - name: Deploy to GitHub Pages
        uses: eclipse-edc/.github/.github/actions/deploy-gh-pages@main
        with:
          publish_dir: public
          token: ${{ secrets.GITHUB_TOKEN }}
