name: publish autodoc

on:
  workflow_call:
    inputs:
      version:
        required: false
        description: "version override"
        type: string

jobs:
  generate-and-deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: eclipse-edc/.github/.github/actions/publish-autodoc@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
