name: Scan Pull Request

on:
  workflow_call:
    secrets:
      envGH:
        required: true

jobs:
  check-pull-request-title:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          # Match pull request titles conventional commit syntax (https://www.conventionalcommits.org/en/v1.0.0/)
          # (online tool for regex quick check: https://regex101.com/r/V5J8kh/1)
          #
          # Valid examples would be
          # - fix: resolve minor issue
          # - docs(Sample5): update docs for configuration
          # - feat(management-api)!: change path to access contract agreements
          #
          # Invalid examples would be
          # - Add cool feature
          # - Feature/some cool improvement
          # - fix: resolve minor issue.
          regex: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(\w+((,|\/|\\)?\s?\w+)+\))?!?: [\S ]{1,80}[^\.]$'
          allowed_prefixes: 'build,chore,ci,docs,feat,fix,perf,refactor,revert,style,test'
          prefix_case_sensitive: true

  check-for-assigned-labels:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: agilepathway/label-checker@v1.6.56
        with:
          any_of: api,bug,build,dependencies,documentation,enhancement,no-changelog,refactoring
          repo_token: ${{ secrets.envGH }}

  review-allowed-licenses:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - name: 'Check Allowed Licenses'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical
          # Representation of this list: https://www.eclipse.org/legal/licenses.php#
          # Expressed with the help of the following IDs: https://spdx.org/licenses/
          allow-licenses: >-
            Adobe-Glyph, Apache-1.0, Apache-1.1, Apache-2.0, Artistic-2.0, BSD-2-Clause, BSD-3-Clause,
            BSD-4-Clause, 0BSD, BSL-1.0, CDDL-1.0, CDDL-1.1, CPL-1.0, CC-BY-3.0, CC-BY-4.0, CC-BY-2.5,
            CC-BY-SA-3.0, CC-BY-SA-4.0, CC0-1.0, EPL-1.0, EPL-2.0, FTL, GFDL-1.3-only, IPL-1.0, ISC,
            MIT, MIT-0, MPL-1.1, MPL-2.0, NTP, OpenSSL, PHP-3.01, PostgreSQL, OFL-1.1, Unlicense,
            Unicode-DFS-2015, Unicode-DFS-2016, Unicode-TOU, UPL-1.0, W3C-20150513, W3C-19980720, W3C,
            WTFPL, X11, Zlib, ZPL-2.1
