name: Release

on:
  workflow_call:

jobs:

  Publish-Artefacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-edc/.github/.github/actions/publish-maven-artifacts@main
        with:
          gpg-private-key: ${{ secrets.ORG_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.ORG_GPG_PASSPHRASE }}
          osshr-username: ${{ secrets.ORG_OSSRH_USERNAME }}
          osshr-password: ${{ secrets.ORG_OSSRH_PASSWORD }}

  Create-Tag:
    needs: [ Publish-Artefacts ]
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.set-tag.outputs.TAG }}
      VERSION: ${{ steps.set-tag.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        id: set-tag
        run: |
          git config user.name "eclipse-edc-bot"
          git config user.email "edc-bot@eclipse.org"
          
          VERSION=$(grep "version" gradle.properties  | awk -F= '{print $2}')
          TAG=v$VERSION
          
          git tag $TAG
          git push origin tag $TAG
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

  Create-GitHub-Release:
    needs: [ Create-Tag ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ needs.Create-Tag.outputs.TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          removeArtifacts: true

  Bump-Version:
    name: 'Update release version'
    needs: [ Create-Tag ]
    if: ${{ endsWith(needs.Create-Tag.outputs.VERSION, '.0') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-edc/.github/.github/actions/bump-version@main
        with:
          base_version: ${{ needs.Create-Tag.outputs.VERSION }}

  Post-To-Discord:
    needs: [ Publish-Artefacts, Create-Tag ]
    if: "always()"
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        name: "Invoke discord webhook"
        with:
          webhook: ${{ secrets.DISCORD_GITHUB_CI_WEBHOOK }}
          # if the publishing is skipped, that means the preceding test run failed
          status: ${{ needs.Publish-Artefacts.result }}
          title: "Release ${{ github.repository }}"
          description: "Build and publish ${{ needs.Create-Tag.outputs.TAG }}"
          username: GitHub Actions

