name: Prepare Release

on:
  workflow_call:
    inputs:
      ref:
        description: the starting ref to create the release branch. If left empty "main" will be used.
        required: false
        type: string
        default: main
      version:
        description: the version to be released. If it ends with '.0' a proper release is created, bugfix otherwise
        required: true
        type: string

jobs:
  Prepare-Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: set release type
        shell: bash
        id: vars
        run: |
          type=bugfix
          if [[ ${{ inputs.version }} == *0 ]] 
          then
            type=release
          fi
          echo "type=$type" >> $GITHUB_OUTPUT

      - name: create ${{ steps.vars.outputs.type }}/${{ inputs.version }} branch
        shell: bash
        run: |
          git config user.name "eclipse-edc-bot"
          git config user.email "edc-bot@eclipse.org"
          
          git checkout -b ${{ steps.vars.outputs.type }}/${{ inputs.version }}
          git push -f origin ${{ steps.vars.outputs.type }}/${{ inputs.version }}

      - shell: bash
        run: |
          # updates the project version
          sed -i 's#^version=.*#version=${{ inputs.version }}#g' $(find . -name "gradle.properties")

          # updates the eventual core library version in the version catalog
          sed -i 's#^edc\s*=\s*.*#edc = "${{ inputs.version }}"#g' gradle/libs.versions.toml

      - name: Create prepare/${{ inputs.version }} branch and commit changes
        run: |
          git config user.name "eclipse-edc-bot"
          git config user.email "edc-bot@eclipse.org"

          git checkout -b prepare/${{ inputs.version }}
          git add .
          git commit -m "Prepare ${{ steps.vars.outputs.type }} ${{ inputs.version }}"
          git push origin prepare/${{ inputs.version }}

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: prepare/${{ inputs.version }}
          base: ${{ steps.vars.outputs.type }}/${{ inputs.version }}
          title: Prepare ${{ steps.vars.outputs.type }} ${{ inputs.version }}
          reviewers: ${{ github.actor }}
          body: |-
            This PR was created in response to a manual trigger of the prepare release.
            Versions have been bumped in to ${{ inputs.version }}.

            Merging this PR will create and run a release workflow
