name: "Create Snapshot Build"

on:
  workflow_call:
    inputs:
      github_repository:
        required: true
        type: string
    secrets:
      jenkins_user:
        required: true
      jenkins_token:
        required: true

jobs:
  Trigger-Snapshot:
    runs-on: ubuntu-latest
    # forks cannot trigger Jenkins
    if: ${{ startsWith( inputs.github_repository, 'eclipse-edc') }}
    steps:
      # Trigger EF Jenkins. This job waits for Jenkins to complete the publishing, which may take a long time, because every
      # module is signed individually, and parallelism is not available. Hence, the increased timeout of 3600 seconds.
      # There is no way to cancel the process on Jenkins from withing GitHub.
      - name: Call Jenkins API to trigger build
        uses: toptal/jenkins-job-trigger-action@master
        with:
          jenkins_url: "https://ci.eclipse.org/edc/"
          jenkins_user: ${{ secrets.jenkins_user }}
          jenkins_token: ${{ secrets.jenkins_token }}
          # empty params are needed, otherwise the job will fail.
          job_params: |
            {
              "REPO": join('https://github.com/', ${{ inputs.github_repository }})
            }
          job_name: "Publish-Component"
          job_timeout: "3600" # Default 30 sec. (optional)
